apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumni-frontend
  template:
    metadata:
      labels:
        app: alumni-frontend
    spec:
      containers:
      - name: frontend
        image: alumni-frontend:1.0 # Ensure this image is accessible to your Kubeadm worker nodes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: alumni-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080