# nginx.conf (MUST BE A SEPARATE FILE)
server {
    listen 80 default_server;  # <-- Add default_server here
    server_name _;             # <-- Change localhost to an underscore

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}